default: &default
  enhance_image_tag: true
  static_image_support: true
  cdn_subdomain: true
  secure_distribution: false
  private_cdn: false

staging:
  <<: *default

production:
  cloud_name: "jh2tc"
  api_key: "888353585318946"
  api_secret: "ECxqFQr3eILaxekBKHnWLPAteYQ"
  secure: true
